const data = {
  id: "template-1751473835162",
  name: "Template Mới",
  description: "Mô tả template mới",
  version: "1.0",
  isDefault: true,
  createdBy: "system",
  createdAt: "2025-07-02T16:30:34.129Z",
  updatedAt: "2025-07-02T16:30:34.129Z",
  metadata: {
    subject: "Hóa học",
    educationLevel: "THPT",
    framework: "GDPT 2018",
  },
  steps: [
    {
      id: "2d1b9ef2-ea1c-4b21-a8b4-9dac9ab2f4e3",
      title: "Thông tin chung",
      description: "Thông tin cơ bản về bài giảng",
      isRequired: true,
      order: 0,
      keywords: [
        {
          id: "679f7318-4724-4436-ab79-290760503640",
          title: "Tên GV",
          content: "",
          order: 0,
          nodeType: "LIST_ITEM",
        },
        {
          id: "690067e9-ae15-4576-9357-6225c423eb00",
          title: "Tên Trường",
          content: "",
          order: 1,
          nodeType: "LIST_ITEM",
        },
        {
          id: "3912b399-bf05-446a-9214-89f2bff5922c",
          title: "Bài",
          content: "",
          order: 2,
          nodeType: "LIST_ITEM",
        },
        {
          id: "f03f8dad-8ce8-4213-8bcc-4da49321ae37",
          title: "Thời Gian",
          content: "",
          order: 3,
          nodeType: "LIST_ITEM",
        },
        {
          id: "a9be5ced-e112-46b1-af04-79bd5c6fda60",
          title: "Lớp",
          content: "",
          order: 4,
          nodeType: "LIST_ITEM",
        },
      ],
      stepType: "general_info",
    },
    {
      id: "a71b81ac-2db5-483e-bf15-5a6f7b5d6f77",
      title: "I. Mục tiêu",
      description: "Mục tiêu kiến thức, năng lực và phẩm chất",
      isRequired: true,
      order: 1,
      keywords: [
        {
          id: "24643eee-2942-4511-be4a-60c51f16ced5",
          title: "1. Kiến thức",
          content: "",
          order: 0,
          children: [
            {
              id: "8b3e3358-f36e-483a-b129-321dac9dbd3b",
              title: "Nhận biết và trình bày được khái niệm…",
              content: "",
              order: 0,
              nodeType: "PARAGRAPH",
            },
            {
              id: "8bdafb15-00a4-4d60-8ea4-0ef8dd52a338",
              title: "Hiểu được bản chất của hiện tượng/sự vật…",
              content: "",
              order: 1,
              nodeType: "PARAGRAPH",
            },
            {
              id: "b12eb4a8-1dbe-495d-93fc-f62dd573704a",
              title: "Phân biệt được các loại…",
              content: "",
              order: 2,
              nodeType: "LIST_ITEM",
            },
            {
              id: "b3e98b56-1722-4a1a-9145-c08244d074d2",
              title: "Vận dụng kiến thức để giải thích…",
              content: "",
              order: 3,
              nodeType: "PARAGRAPH",
            },
            {
              id: "159535e9-6d63-465c-a888-dea0ccdbacb4",
              title: "Phân tích được ưu điểm/nhược điểm của…",
              content: "",
              order: 4,
              nodeType: "LIST_ITEM",
            },
            {
              id: "d291ac0a-9218-49a9-905b-20ff64b7a5a2",
              title: "So sánh được đặc điểm của…",
              content: "",
              order: 5,
              nodeType: "LIST_ITEM",
            },
            {
              id: "a869dadd-12d5-47f9-9cae-5b54b4027436",
              title: "Ứng dụng kiến thức đã học vào thực tiễn…",
              content: "",
              order: 6,
              nodeType: "PARAGRAPH",
            },
          ],
          nodeType: "SECTION",
        },
        {
          id: "2ad481cb-87c0-471b-9d8c-27a12a55b4f1",
          title: "2. Năng lực",
          content: "",
          order: 1,
          children: [
            {
              id: "0895e719-3228-4294-acc7-c1b761d808d5",
              title: "2.1. Năng lực chung",
              content: "",
              order: 0,
              children: [
                {
                  id: "f981192c-6c63-475a-96c5-a198972bea25",
                  title: "Năng lực tự chủ và tự học: ...",
                  content: "",
                  order: 0,
                  nodeType: "LIST_ITEM",
                },
                {
                  id: "b1e6438d-bcb4-42a6-a4fa-e8c5109c01ea",
                  title: "Năng lực giao tiếp và hợp tác: ...",
                  content: "",
                  order: 1,
                  nodeType: "LIST_ITEM",
                },
                {
                  id: "4567f7b7-48c1-4b88-9810-88aaf0e52163",
                  title: "Giải quyết vấn đề và sáng tạo: ...",
                  content: "",
                  order: 2,
                  nodeType: "LIST_ITEM",
                },
              ],
              nodeType: "LIST_ITEM",
            },
            {
              id: "7e4d1941-879f-4bf7-befb-cd7f512e8551",
              title: "2.2. Năng lực hóa học",
              content: "",
              order: 1,
              children: [
                {
                  id: "79d9af4b-4928-4860-be23-18d70b638ab8",
                  title: "a. Nhận thức hóa học",
                  content: "",
                  order: 0,
                  children: [
                    {
                      id: "d71d07e2-880f-4526-a595-a386ab72b71c",
                      title: "Nhận biết, mô tả hiện tượng hóa học",
                      content: "",
                      order: 0,
                      nodeType: "LIST_ITEM",
                    },
                    {
                      id: "ee6cb6d2-c5b1-4ae5-a650-9525e3262c03",
                      title: "Hiểu được các khái niệm chuyên ngành",
                      content: "",
                      order: 1,
                      nodeType: "LIST_ITEM",
                    },
                  ],
                  nodeType: "LIST_ITEM",
                },
                {
                  id: "75c9b045-a82a-423b-ae9f-0611556a4c2b",
                  title: "b. Tìm hiểu tự nhiên dưới góc độ hóa học",
                  content: "",
                  order: 1,
                  nodeType: "LIST_ITEM",
                },
                {
                  id: "1a807c17-3bbc-43f9-8187-0b8880016c08",
                  title:
                    "c. Vận dụng kiến thức, kĩ năng đã học để giải thích được",
                  content: "",
                  order: 2,
                  nodeType: "LIST_ITEM",
                },
              ],
              nodeType: "LIST_ITEM",
            },
          ],
          nodeType: "LIST_ITEM",
        },
        {
          id: "0b174531-dd17-426b-9387-cc023735083b",
          title: "3. Phẩm chất",
          content: "",
          order: 2,
          children: [
            {
              id: "98ccb4c9-763a-4786-9e0d-cdbea63c405e",
              title: "Trách nhiệm:",
              content: "",
              order: 0,
              nodeType: "LIST_ITEM",
            },
            {
              id: "d6afbdf8-e301-4a91-b39c-49c0fd8e1755",
              title: "Trung thực:",
              content: "",
              order: 1,
              nodeType: "LIST_ITEM",
            },
            {
              id: "0c9c5280-7347-4e6a-830c-2a0c0bdfe732",
              title: "Chăm chỉ:",
              content: "",
              order: 2,
              nodeType: "LIST_ITEM",
            },
            {
              id: "59e07ba5-7b8b-4c2f-950f-ddd4d1b118d9",
              title: "Nhân ái:",
              content: "",
              order: 3,
              nodeType: "LIST_ITEM",
            },
          ],
          nodeType: "LIST_ITEM",
        },
      ],
      stepType: "objectives",
    },
    {
      id: "c7e00fdc-b568-44dd-83c4-ffdc7f0eed91",
      title: "II. Thiết bị dạy học và học liệu",
      description: "Thiết bị và tài liệu cần thiết cho bài học",
      isRequired: true,
      order: 2,
      keywords: [
        {
          id: "a847ce88-e417-4875-ab57-b9f32d9fa903",
          title: "1. Giáo viên",
          content: "",
          order: 0,
          children: [
            {
              id: "ccfbd21a-4326-4f27-bea7-56133b5dc8b8",
              title: "Một số hình ảnh:",
              content: "",
              order: 0,
              nodeType: "LIST_ITEM",
            },
            {
              id: "518cc011-ef60-4466-8a19-26d9cc79eb40",
              title: "Video mô hình nguyên tử",
              content: "",
              order: 1,
              nodeType: "LIST_ITEM",
            },
            {
              id: "5033ab4c-3d64-4455-a70c-47e3f9f3b8b9",
              title: "Công cụ dạy học ..",
              content: "",
              order: 2,
              nodeType: "LIST_ITEM",
            },
            {
              id: "ba163968-0948-41c1-a241-33ca41e36588",
              title: "SGK nào",
              content: "",
              order: 3,
              nodeType: "LIST_ITEM",
            },
          ],
          nodeType: "LIST_ITEM",
        },
        {
          id: "ca5f5bf6-7db4-46d5-a861-f5a12858ccad",
          title: "2. Học sinh",
          content: "",
          order: 1,
          children: [
            {
              id: "b45da644-c07c-4400-b8cc-d09870de8851",
              title: "SGK",
              content: "",
              order: 0,
              nodeType: "LIST_ITEM",
            },
            {
              id: "80893780-d45d-4bfd-880a-cf79762c4a2e",
              title: "Đồ dùng học tập",
              content: "",
              order: 1,
              nodeType: "LIST_ITEM",
            },
            {
              id: "ecd87eb3-8c73-4458-87c7-b82e65f15c77",
              title: "Bảng tuần hoàn nguyên tố hóa học",
              content: "",
              order: 2,
              nodeType: "LIST_ITEM",
            },
          ],
          nodeType: "LIST_ITEM",
        },
      ],
      stepType: "equipment",
    },
    {
      id: "76e1e942-93de-42c9-9e2a-c25856a0c946",
      title: "III. TIẾN TRÌNH DẠY HỌC",
      description: "Các hoạt động trong tiến trình dạy học",
      isRequired: true,
      order: 3,
      keywords: [
        {
          id: "d07e3893-0014-4527-bf01-46c654dee250",
          title: "1. Hoạt động 1: Khởi động",
          content: "X phút",
          order: 0,
          children: [
            {
              id: "9a30632d-fbc1-48c7-942a-62e5876365e3",
              title: "a. Mục tiêu",
              content: "Tạo hứng thú và kích thích sự tò mò của học sinh",
              order: 0,
              nodeType: "LIST_ITEM",
            },
            {
              id: "a43c610e-4bfa-43ce-9bfc-cd67ad05cbc4",
              title: "b. Nội dung",
              content: "",
              order: 1,
              children: [
                {
                  id: "044aa4b8-40ea-402e-8a0a-568bd12957dd",
                  title: "CÂU HỎI KHỞI ĐỘNG:",
                  content: "",
                  order: 0,
                  nodeType: "LIST_ITEM",
                },
                {
                  id: "70a7303a-1f3e-44f9-8377-e4d93ff052f5",
                  title: "Hình ảnh, video",
                  content: "",
                  order: 1,
                  nodeType: "LIST_ITEM",
                },
                {
                  id: "2f681856-1886-4a13-85a4-92fbe54c994e",
                  title: "Mô hình",
                  content: "",
                  order: 2,
                  nodeType: "LIST_ITEM",
                },
                {
                  id: "cb7eda4c-39fb-4911-b38a-6c724d804dde",
                  title: "Câu đố",
                  content: "",
                  order: 3,
                  nodeType: "LIST_ITEM",
                },
              ],
              nodeType: "LIST_ITEM",
            },
            {
              id: "fa302fd9-ce53-46af-8354-c1b072ba55db",
              title: "c. Sản phẩm",
              content: "DỰ KIẾN TRẢ LỜI CÂU HỎI KHỞI ĐỘNG",
              order: 2,
              nodeType: "LIST_ITEM",
            },
            {
              id: "b39028fc-1634-4cf6-b043-9a6e9eed895b",
              title: "d. Tổ chức thực hiện",
              content: "",
              order: 3,
              children: [
                {
                  id: "d601f037-edcb-4377-85fd-3f3de4d64783",
                  title: "HOẠT ĐỘNG CỦA GIÁO VIÊN",
                  content: "",
                  order: 0,
                  children: [
                    {
                      id: "18a4ff79-1aa3-4126-b432-1104f7974c76",
                      title: "Bước 1: Chuyển giao nhiệm vụ học tập",
                      content: "",
                      order: 0,
                      nodeType: "LIST_ITEM",
                    },
                    {
                      id: "391b2a33-b7cb-4d8e-baef-7da0a21cae60",
                      title: "Bước 2: Thực hiện nhiệm vụ",
                      content: "",
                      order: 1,
                      nodeType: "LIST_ITEM",
                    },
                    {
                      id: "7fc65a84-d744-4162-84d5-c3dc97fad26a",
                      title: "Bước 3: Báo cáo kết quả và thảo luận",
                      content: "",
                      order: 2,
                      nodeType: "LIST_ITEM",
                    },
                    {
                      id: "7572caf8-70f6-4b7d-9c26-46860c4454fc",
                      title: "Bước 4: Kết luận và nhận định",
                      content: "",
                      order: 3,
                      nodeType: "LIST_ITEM",
                    },
                  ],
                  nodeType: "LIST_ITEM",
                },
                {
                  id: "56454ad8-53eb-4a74-ae37-b228700855b5",
                  title: "HOẠT ĐỘNG CỦA HỌC SINH",
                  content: "",
                  order: 1,
                  children: [
                    {
                      id: "568b6a1b-07cf-4c13-93dc-3f19e2cac198",
                      title: "Lắng nghe, nhận nhiệm vụ",
                      content: "",
                      order: 0,
                      nodeType: "LIST_ITEM",
                    },
                    {
                      id: "fc964447-c803-498d-899f-f1c4d04a6bf3",
                      title: "Thảo luận, nghiên cứu, quan sát",
                      content: "",
                      order: 1,
                      nodeType: "LIST_ITEM",
                    },
                    {
                      id: "eaeb74b3-5c1a-4ec8-8993-efa298b0df18",
                      title: "Trình bày kết quả thảo luận",
                      content: "",
                      order: 2,
                      nodeType: "LIST_ITEM",
                    },
                    {
                      id: "e8700c63-e35a-4658-ace3-e33f85fa402f",
                      title: "Lắng nghe, tiếp thu nhận xét",
                      content: "",
                      order: 3,
                      nodeType: "LIST_ITEM",
                    },
                  ],
                  nodeType: "LIST_ITEM",
                },
              ],
              nodeType: "LIST_ITEM",
            },
          ],
          nodeType: "LIST_ITEM",
        },
        {
          id: "b6b3632d-cd16-42c9-8547-3c1921cece3c",
          title: "2. Hoạt động 2: Hình thành kiến thức mới",
          content: "X phút",
          order: 1,
          nodeType: "LIST_ITEM",
        },
        {
          id: "d71ed6d1-3144-41f4-9f4e-85a1585ede5f",
          title: "3. Hoạt động 3: Luyện tập",
          content: "X phút",
          order: 2,
          nodeType: "LIST_ITEM",
        },
        {
          id: "3caa05c9-6adc-4ac2-ad71-a6eb9cd944de",
          title: "4. Hoạt động 4: Vận dụng",
          content: "X phút",
          order: 3,
          nodeType: "LIST_ITEM",
        },
      ],
      stepType: "activities",
      timeAllocation: 45,
    },
  ],
};
